---
title: "PS270 Final Project"
author: "Clayton Elsbree"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how Democracy and Wealth are correlated. I would like to see how the two influence each other, and which one might cause the other.


## Loading Data 

```{r}
library(haven)
cpds <- read_dta("CPDS_1960-2023_Update_2025.dta")
head(cpds)
```


## Proposal

I will be using data from a comparative politics data set, which contains data from 1960- 2025 for 36 democratic countries. There is both political and economic data in this set. My research question is does more positions held by left-wing parties in government lead to higher levels of government spending? I hypothesize as the share of left-wing cabinet participants increase, total government spending as a percentage of GDP will also increase. This expectation is rooted in the theory that left-winged governments typically represent lower income constituencies and therefore favor policies that lead to redistribution and a larger welfare system. The explanatory variable of interest is gov_left_1, which shows the percentage of cabinet positions held by social democratic and other left sided parties in a given year in the given country. This variable is varies both across countries and over time, allowing for meaningful statistical comparisons to be made. The outcome variable is outlays, which tracks total government expenditures as a percentage of the GDP for the given year. If I observe a positive relationship between the two variables, this would support my hypothesis. However, if the relationship is neutral or negative this would provide evidence against the theory that left-winged governments produce higher levels of government spending.
